#sentences neutral 0, positive 1, negative 2

sentences=[
(0, 'in-patient or day-patient Private hospital and day-patient unit fees  For more information see Section 3  -  Paid in full so long as you use a hospital or day-patient unit in your Directory of Hospitals Including fees for in-patient or day-patient:  accommodation  diagnostic tests  using the operating theatre  nursing care  drugs  dressings  radiotherapy and chemotherapy  physiotherapy  surgical appliances that the specialist uses during surgery.'),
(1, 'Fees for out-patient treatment by physiotherapists acupuncturists homeopaths osteopaths or chiropractors No yearly limit on fees up to a combined overall maximum of 10 sessions in a scheme year when your GP refers you or you have therapist treatment through our Working Body team We call physiotherapists osteopaths and chiropractors therapists.'),
(1, 'Immediate emergency in-patient treatment received while travelling abroad which relates to an evacuation or repatriation we have arranged for you Paidin full up to £40000 a scheme year  1 Quick start guide to your membership Advance membership handbook  Page 9 Additional benefits External prosthesis Up to£5000 for the lifetime of your membership The trustee will pay this benefit towards the cost of providing an external prosthesis.'),
(0, 'For details see Section 4  External prostheses and appliances  Benefit limitation information Benefit limitation per member per scheme year £100 Benefit limitations do not apply to:  Overseas evacuation and repatriation service  NHS cash benefit  Day-patient and out-patient radiotherapy and chemotherapy cash benefit  Parent hotel accommodation  Counselling arranged through Stronger Minds  External prostheses  Cancer cover and care For details see Section 4 - Cancer.'),
(1, '2 Making a claim and using your Advance services Advance membership handbook  Page 12   Working Body  for muscle bone and joint conditions 0800 092 8441   Working Body makes it easy for you to get expert physiotherapy services fast.'),
(1, 'Call us on 0800 092 8441 - As soon as you develop a problem you can call your Personal Advisory team to check your cover and arrange a clinical needs assessment with a physiotherapist over the phone.'),
(1, 'Assessments available 8am to 6pm Monday to Friday Initial clinical needs assessment - During the phone call the physiotherapist will listen to your concerns and take you through an initial assessment.'),
(1, 'After the assessment The physiotherapist will recommend treatment which could be one of three options:  Self-management   you with easy to follow guidance on how best to manage your condition.'),
(1, 'Treatment with a physiotherapist osteopath or chiropractor    Referral on to a specialist  we can arrange for you to see a private specialist through our Fast Track Appointments service.'),
(1, 'Extensive panel including doctors psychologists nurses physiotherapists and dieticians  Support from our Dedicated Nurse Services Personal support after diagnosis of a heart condition or cancer Our members have access to our Dedicated Nurse Service 24/7 365 days a year.'),
(1, 'The trustee will pay out-patient treatment fees for any of the following we recognise so long as your treatment is covered and the Working Body team your GP or specialist refers you:  physiotherapists  osteopaths  chiropractors.'),
(1, 'The trustee pays physiotherapists osteopaths and chiropractors in full if we recognise them.'),
(1, 'In-patient and day-patient hospital fees include costs'),
(1, 'In-patient and day-patient hospital fees include costs for things like:  accommodation  diagnostic tests  using the operating theatre  nursing care  drugs  dressings  radiotherapy and chemotherapy  physiotherapy  surgical appliances that the specialist uses during surgery.'),
(2, '3 How your membership works Advance membership handbook  Page 24 3.9 General restrictions High charges The trustee will not pay if any of the following charge a significant amount more than they usually do unless we have agreed this beforehand:  a specialist -  a physiotherapist  an osteopath  a chiropractor.'),
(1, '4.11 External prostheses or appliances The trustee will pay up to £5000 towards the cost of an external prosthesis needed following an accident or surgery for a medical condition.'),
(2, 'This is so long as:  you had a medically documented accident or medical condition that has led to the need for the prosthesis; and  all claims are made within 12 months of the amputation or removal of the body part.'),
(2, 'Please remember to ask the provider of your external prosthesis for full receipts as we cannot pay claims without receipts.'),
(2, 'Some examples of the conditions we do not cover are the following please call if you would like to know if a condition is covered:  dyslexia  dyspraxia  autistic spectrum disorder  attention deficit hyperactivity disorder ADHD  speech and language problems including speech therapy needed because of another medical condition.'),
(0, 'external prosthesis - an artificial removable replacement for a part of the body.'),
(2, "The trustee will not pay for speech therapy"),
(2, "General restrictions High charges The trustee will not pay if any of the following charge a significant amount more than they usually do unless we have agreed this beforehand:  a specialist -  a physiotherapist  an osteopath  a chiropractor."),
(2, "The trustee will not pay for physiotherapy"),
(2, "The trustee will not pay for treatment"),
(2, "Benefit limitation per member per scheme year "),
(2, "The trustee does not cover dyslexia  dyspraxia  autistic spectrum disorder"),
(2, "The trustee does not cover attention deficit hyperactivity disorder ADHD"),
(1, "No yearly limit on fees"),
(1, "Our members have access to our Dedicated Nurse Service 24/7 365 days a year."),
(1, "Extensive panel including doctors psychologists nurses physiotherapists and dieticians"),
(1,"we can arrange for you to see a private specialist through our Fast Track Appointments service."),
(1, "The trustee will  pay for speech therapy"),
(1, "The trustee will pay for physiotherapy"),
(1, "The trustee will pay for treatment"),
(1, "The trustee does cover dyslexia  dyspraxia  autistic spectrum disorder"),
(1, "The trustee does cover attention deficit hyperactivity disorder ADHD"),
(2, 'Conditions we do not cover are:  dyslexia  dyspraxia  autistic spectrum disorder  attention deficit hyperactivity disorder ADHD  speech and language problems including speech therapy needed because of another medical condition.'),
(0, 'therapist  a medical practitioner who meets all of the following conditions:  is a practitioner in physiotherapy osteopathy chiropractic treatment  is fully registered under the relevant Acts  is recognised by us as a therapist for out-patient treatment.')]

